In [3]:
import pandas as pd
df=pd.read_csv("food_delivery_data.csv")
df.head(8)

,OrderID,OrderDate,OrderTime,Location,FoodItem,Quantity,Price,CustomerRating
0,1,24-11-2025,03:01,Madurai,Paneer Butter Masala,3,182.85,3.3
1,2,13-12-2025,23:57,Madurai,Pasta,1,328.01,3.1
2,3,22-04-2025,07:32,Tirunelveli,Sandwich,1,315.72,4.4
3,4,07-10-2025,13:14,Chennai,Noodles,5,196.84,4.7
4,5,24-12-2025,13:21,Madurai,Idli,2,170.43,4.5
5,6,17-02-2025,12:06,Tirunelveli,Fried Rice,3,333.56,4.6
6,7,24-08-2025,17:07,Salem,Parotta,1,311.86,4.7
7,8,05-07-2025,18:12,Coimbatore,Paneer Butter Masala,1,99.25,3.5

In [4]:
df.tail(8)

,OrderID,OrderDate,OrderTime,Location,FoodItem,Quantity,Price,CustomerRating
992,993,13-05-2025,05:37,Chennai,Biryani,2,214.27,4.8
993,994,02-07-2025,05:03,Coimbatore,Idli,3,256.20,4.8
994,995,25-01-2025,09:18,Chennai,Pasta,1,295.82,4.5
995,996,18-02-2025,19:48,Tirunelveli,Burger,5,215.49,3.6
996,997,04-06-2025,08:43,Chennai,Paneer Butter Masala,3,120.25,4.2
997,998,07-01-2025,04:33,Chennai,Idli,3,407.10,3.8
998,999,22-02-2025,06:09,Salem,Pasta,2,429.26,4.6
999,1000,11-11-2025,22:53,Madurai,Pasta,5,379.27,4.4