In [9]:
import pandas as pd
df=pd.read_csv("food_delivery_data.csv")
df.head()

,OrderID,OrderDate,OrderTime,Location,FoodItem,Quantity,Price,CustomerRating
0,1,24-11-2025,03:01,Madurai,Paneer Butter Masala,3,182.85,3.3
1,2,13-12-2025,23:57,Madurai,Pasta,1,328.01,3.1
2,3,22-04-2025,07:32,Tirunelveli,Sandwich,1,315.72,4.4
3,4,07-10-2025,13:14,Chennai,Noodles,5,196.84,4.7
4,5,24-12-2025,13:21,Madurai,Idli,2,170.43,4.5

In [10]:
import pandas as pd
df=pd.read_csv("food_delivery_data.csv")
df.tail()

,OrderID,OrderDate,OrderTime,Location,FoodItem,Quantity,Price,CustomerRating
995,996,18-02-2025,19:48,Tirunelveli,Burger,5,215.49,3.6
996,997,04-06-2025,08:43,Chennai,Paneer Butter Masala,3,120.25,4.2
997,998,07-01-2025,04:33,Chennai,Idli,3,407.10,3.8
998,999,22-02-2025,06:09,Salem,Pasta,2,429.26,4.6
999,1000,11-11-2025,22:53,Madurai,Pasta,5,379.27,4.4

In [1]:
import pandas as pd
df=pd.read_csv("food_delivery_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         1000 non-null   int64
 1   OrderDate       1000 non-null   object
 2   OrderTime       1000 non-null   object
 3   Location        1000 non-null   object
 4   FoodItem        1000 non-null   object
 5   Quantity        1000 non-null   int64
 6   Price           1000 non-null   float64
 7   CustomerRating  1000 non-null   float64
dtypes: float64(2), int64(2), object(4)
memory usage: 62.6+ KB

In [3]:
import pandas as pd
df=pd.read_csv("food_delivery_data.csv")
df.describe()

           OrderID     Quantity        Price  CustomerRating
count  1000.000000  1000.000000  1000.000000     1000.000000
mean    500.500000     3.030000   282.255370        4.028100
std     288.819436     1.416724   122.110791        0.565332
min       1.000000     1.000000    80.460000        3.000000
25%     250.750000     2.000000   178.437500        3.600000
50%     500.500000     3.000000   275.140000        4.000000
75%     750.250000     4.000000   384.572500        4.500000
max    1000.000000     5.000000   499.830000        5.000000

In [7]:
import pandas as pd
df=pd.read_csv("food_delivery_data.csv")
df.columns

Index(['OrderID', 'OrderDate', 'OrderTime', 'Location', 'FoodItem', 'Quantity',
       'Price', 'CustomerRating'],
      dtype='object')